name: Build

on: [push, pull_request]

jobs:
  build-cmake:
    strategy:
      fail-fast: false
      matrix:
        include:
            - name: Windows
              os: windows-latest
            - name: Ubuntu
              os: ubuntu-latest
            - name: Emscripten
              os: ubuntu-latest
            - name: MacOS
              os: macOS-latest
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Prepare cmake
      uses: lukka/get-cmake@latest

    - name: Run vcpkg
      uses: lukka/run-vcpkg@v11

    - name: Prepare emscripten
      if: matrix.name == 'Emscripten'
      uses: mymindstorm/setup-emsdk@v14

    - name: Prepare Ubuntu
      if: contains(matrix.os, 'ubuntu')
      run: |
        sudo apt update -y
        sudo apt install cmake ninja-build -y

    - name: Prepare MacOS
      if: contains(matrix.os, 'macOS')
      run: |
        brew install ninja

    - name: Config cmake(Ubuntu&MacOS)
      if: ${{ !contains(matrix.os, 'windows') && matrix.name != 'Emscripten' }}
      run: |
        ${{ matrix.cmake-path }}cmake --preset=CI-Linux

    - name: Config cmake(Emscripten)
      if: matrix.name == 'Emscripten'
      run: |
        emcmake cmake --preset=CI-Emscripten

    - name: Config cmake(Windows)
      if: contains(matrix.os, 'windows')
      run: |
        ${{ matrix.cmake-path}}cmake --preset=CI-Windows

    - name: Build under PC
      run: ${{ matrix.cmake-path }}cmake --build cmake-build
