name: Build

on: [push, pull_request]

jobs:
  build-cmake:
    strategy:
      fail-fast: false
      matrix:
        include:
            - name: Windows
              os: windows-latest
              android: none
            - name: Ubuntu
              os: ubuntu-latest
              android: none
            - name: Emscripten
              os: ubuntu-latest
              android: none
            - name: MacOS
              os: macOS-latest
              android: none
            - name: Android
              os: ubuntu-latest
              android: arm64
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Prepare cmake
      uses: lukka/get-cmake@latest

    - name: Run vcpkg
      if: matrix.android == 'none'
      uses: lukka/run-vcpkg@v11

    - name: Prepare emscripten
      if: matrix.name == 'Emscripten'
      uses: mymindstorm/setup-emsdk@v14

    - name: Prepare Ubuntu
      if: contains(matrix.os, 'ubuntu') && matrix.android == 'none'
      run: |
        sudo apt update -y
        sudo apt install cmake ninja-build -y

    - name: Prepare MacOS
      if: contains(matrix.os, 'macOS')
      run: |
        brew install ninja

    - name: Config cmake(Ubuntu&MacOS)
      working-directory: ./game
      if: ${{ !contains(matrix.os, 'windows') && matrix.android == 'none' && matrix.name != 'Emscripten' }}
      run: |
        ${{ matrix.cmake-path }}cmake --preset=CI-Linux

    - name: Config cmake(Emscripten)
      working-directory: ./game
      if: matrix.name == 'Emscripten'
      run: |
        emcmake cmake --preset=CI-Emscripten

    - name: Config cmake(Windows)
      working-directory: ./game
      if: contains(matrix.os, 'windows')
      run: |
        ${{ matrix.cmake-path}}cmake --preset=CI-Windows

    - name: Build under PC
      working-directory: ./game
      if: matrix.android == 'none'
      run: ${{ matrix.cmake-path }}cmake --build cmake-build

    - name: Prepare Android JDK
      if: runner.os == 'Linux' && matrix.android != 'none'
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Prepare Android Project
      if: runner.os == 'Linux' && matrix.android != 'none'
      run: |
        git submodule update --init --recursive
        sudo apt update -y
        sudo apt install cmake ninja-build -y
        cp -r ./game ./android/app/jni/
        chmod +x ./android/gradlew

    - name: Build under Android
      if: runner.os == 'Linux' && matrix.android != 'none'
      working-directory: ./android
      run: |
        ninja --version
        ./gradlew build
